services:
  - type: web
    plan: free
    name: fastapi-app
    runtime: python
    repo: https://github.com/valerianomacuri/fastapi-crash-course.git
    buildCommand: 'uv install'
    startCommand: 'python -m gunicorn app.main:app -k uvicorn.workers.UvicornWorker'
